# -*- coding: utf-8 -*-
"""Task3_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqCG7UBJmjgNYwMvnoNX96leCHg2BGgo
"""

!pip install nltk

import nltk
nltk.download('punkt')

while True:
    user = input("You: ").lower()

    if "hello" in user:
        print("Bot: Hello! How can I help you?")

    elif "name" in user:
        print("Bot: I am your internship chatbot.")

    elif "python" in user:
        print("Bot: Python is a programming language.")

    elif "bye" in user:
        print("Bot: Goodbye!")
        break

    else:
        print("Bot: Sorry, I don't understand.")