# -*- coding: utf-8 -*-
"""Task4_ML_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkRCx-K_xYIql8N7IFKszL1aPbtd4uZs
"""

!pip install scikit-learn pandas

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

texts = [
    "free money now",
    "win cash prize",
    "hello friend",
    "meeting tomorrow",
    "claim your reward",
    "project discussion"
]

labels = [1, 1, 0, 0, 1, 0]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

model = MultinomialNB()
model.fit(X, labels)

test = vectorizer.transform(["free prize"])
prediction = model.predict(test)

print(prediction)

test = vectorizer.transform(["free prize"])
prediction = model.predict(test)

if prediction[0] == 1:
    print("Spam Message")
else:
    print("Not Spam")

test = vectorizer.transform(["meeting today"])
prediction = model.predict(test)

if prediction[0] == 1:
    print("Spam Message")
else:
    print("Not Spam")

from sklearn.metrics import accuracy_score

predictions = model.predict(X)

print("Accuracy:", accuracy_score(labels, predictions))