# -*- coding: utf-8 -*-
"""Task1_API_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s--aUc8aI8ErAd-4uhSp5-XfXtMtM1Ln
"""

import requests
import matplotlib.pyplot as plt

api_key = "8c8ee3d2add0b1c965cc2ebd5e95269d"
city = "Mysore"

url = f"https://api.openweathermap.org/data/2.5/forecast?q={city}&appid={api_key}&units=metric"

response = requests.get(url)
data = response.json()

print(data)

api_key = "8c8ee3d2add0b1c965cc2ebd5e95269d"

data['list']

temps = []
times = []

for item in data['list'][:8]:
    temps.append(item['main']['temp'])
    times.append(item['dt_txt'])

print(temps)
print(times)

plt.figure(figsize=(10,5))
plt.plot(times, temps, marker='o')

plt.title("Temperature Forecast for Mysore")
plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.xticks(rotation=45)
plt.savefig("weather_graph.png")
plt.show()

