# -*- coding: utf-8 -*-
"""Task2_PDF_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pja5OXBpTb-W_iZNZNm5TmfiE09rgd9L
"""

!pip install pandas fpdf

import pandas as pd

data = {
    'Name': ['Rahul', 'Anita', 'John'],
    'Math': [80, 85, 70],
    'Science': [75, 88, 65],
    'English': [90, 92, 78]
}

df = pd.DataFrame(data)

df.to_csv('marks.csv', index=False)

print(df)

df = pd.read_csv('marks.csv')
print(df)

average = df.mean(numeric_only=True)

print("Average Marks:")
print(average)

from fpdf import FPDF

pdf = FPDF()
pdf.add_page()

pdf.set_font("Arial", size=12)

pdf.cell(200, 10, txt="Student Marks Report", ln=True, align='C')

pdf.ln(10)

for subject in average.index:
    pdf.cell(200, 10, txt=f"{subject} Average: {average[subject]:.2f}", ln=True)

pdf.output("student_report.pdf")